### ISSUE TITLE
restart loop detected

### ISSUE THREAD

**Issue by Negalein** [iobroker-community-adapters/ioBroker.bayernluft#56]
Adapter: 2.0.0 alpha
Admin: 7.4.3
Node.js: v20.18.1
NPM: 10.8.2
JS-Controller: 7.0.3

jetzt kommen Fehler

```
2024-12-08 16:03:03.149 - info: host.ioBroker iobroker url https://github.com/iobroker-community-adapters/ioBroker.bayernluft --host ioBroker --debug
2024-12-08 16:03:04.767 - info: host.ioBroker iobroker install iobroker-community-adapters/ioBroker.bayernluft#a4b5fc04bfc1c1af3352cdc49ed7e5263d44c568
2024-12-08 16:03:04.872 - info: host.ioBroker iobroker NPM version: 10.8.2Installing iobroker-community-adapters/ioBroker.bayernluft#a4b5fc04bfc1c1af3352cdc49ed7e5263d44c568... (System call)
2024-12-08 16:03:08.756 - info: host.ioBroker iobroker npm warn skipping integrity check for git dependency ssh://git@github.com/iobroker-community-adapters/ioBroker.bayernluft.git
2024-12-08 16:03:10.222 - info: host.ioBroker iobroker upload [12] bayernluft.admin /opt/iobroker/node_modules/iobroker.bayernluft/admin/bayernluft.png bayernluft.png image/png
2024-12-08 16:03:10.233 - info: host.ioBroker iobroker upload [11] bayernluft.admin /opt/iobroker/node_modules/iobroker.bayernluft/admin/i18n/de/translations.json i18n/de/translations.json application/json
2024-12-08 16:03:10.243 - info: host.ioBroker iobroker upload [10] bayernluft.admin /opt/iobroker/node_modules/iobroker.bayernluft/admin/i18n/en/translations.json i18n/en/translations.json application/json
2024-12-08 16:03:10.250 - info: host.ioBroker iobroker upload [9] bayernluft.admin /opt/iobroker/node_modules/iobroker.bayernluft/admin/i18n/es/translations.json i18n/es/translations.json application/json
2024-12-08 16:03:10.260 - info: host.ioBroker iobroker upload [8] bayernluft.admin /opt/iobroker/node_modules/iobroker.bayernluft/admin/i18n/fr/translations.json i18n/fr/translations.json application/json
2024-12-08 16:03:10.264 - info: host.ioBroker iobroker upload [7] bayernluft.admin /opt/iobroker/node_modules/iobroker.bayernluft/admin/i18n/it/translations.json i18n/it/translations.json application/json
2024-12-08 16:03:10.280 - info: host.ioBroker iobroker upload [6] bayernluft.admin /opt/iobroker/node_modules/iobroker.bayernluft/admin/i18n/nl/translations.json i18n/nl/translations.json application/json
2024-12-08 16:03:10.286 - info: host.ioBroker iobroker upload [5] bayernluft.admin /opt/iobroker/node_modules/iobroker.bayernluft/admin/i18n/pl/translations.json i18n/pl/translations.json application/json
2024-12-08 16:03:10.297 - info: host.ioBroker iobroker upload [4] bayernluft.admin /opt/iobroker/node_modules/iobroker.bayernluft/admin/i18n/pt/translations.json i18n/pt/translations.json application/json
2024-12-08 16:03:10.299 - info: host.ioBroker iobroker upload [3] bayernluft.admin /opt/iobroker/node_modules/iobroker.bayernluft/admin/i18n/ru/translations.json i18n/ru/translations.json application/json
2024-12-08 16:03:10.302 - info: host.ioBroker iobroker upload [2] bayernluft.admin /opt/iobroker/node_modules/iobroker.bayernluft/admin/i18n/uk/translations.json i18n/uk/translations.json application/json
2024-12-08 16:03:10.304 - info: host.ioBroker iobroker upload [1] bayernluft.admin /opt/iobroker/node_modules/iobroker.bayernluft/admin/i18n/zh-cn/translations.json i18n/zh-cn/translations.json application/json
2024-12-08 16:03:10.319 - info: host.ioBroker iobroker upload [0] bayernluft.admin /opt/iobroker/node_modules/iobroker.bayernluft/admin/jsonConfig.json jsonConfig.json application/json
2024-12-08 16:03:10.323 - info: host.ioBroker iobroker Updating objects from io-package.json for adapter "bayernluft" with version "2.0.0-alpha.0"
2024-12-08 16:03:19.355 - info: host.ioBroker iobroker add bayernluft auto --host ioBroker --debug
2024-12-08 16:03:20.690 - info: host.ioBroker iobroker host.ioBroker create instance bayernluft
2024-12-08 16:03:20.704 - info: host.ioBroker iobroker host.ioBroker object system.adapter.bayernluft.0.alive created
2024-12-08 16:03:20.712 - info: host.ioBroker iobroker host.ioBroker object system.adapter.bayernluft.0.connected created
2024-12-08 16:03:20.724 - info: host.ioBroker iobroker host.ioBroker object system.adapter.bayernluft.0.compactMode created
2024-12-08 16:03:20.732 - info: host.ioBroker iobroker host.ioBroker object system.adapter.bayernluft.0.cpu created
2024-12-08 16:03:20.740 - info: host.ioBroker iobroker host.ioBroker object system.adapter.bayernluft.0.cputime created
2024-12-08 16:03:20.751 - info: host.ioBroker iobroker host.ioBroker object system.adapter.bayernluft.0.memHeapUsed created
2024-12-08 16:03:20.757 - info: host.ioBroker iobroker host.ioBroker object system.adapter.bayernluft.0.memHeapTotal created
2024-12-08 16:03:20.760 - info: host.ioBroker iobroker host.ioBroker object system.adapter.bayernluft.0.memRss created
2024-12-08 16:03:20.764 - info: host.ioBroker iobroker host.ioBroker object system.adapter.bayernluft.0.uptime created
2024-12-08 16:03:20.768 - info: host.ioBroker iobroker host.ioBroker object system.adapter.bayernluft.0.inputCount created
2024-12-08 16:03:20.772 - info: host.ioBroker iobroker host.ioBroker object system.adapter.bayernluft.0.outputCount created
2024-12-08 16:03:20.776 - info: host.ioBroker iobroker host.ioBroker object system.adapter.bayernluft.0.eventLoopLag created
2024-12-08 16:03:20.782 - info: host.ioBroker iobroker host.ioBroker object system.adapter.bayernluft.0.sigKill created
2024-12-08 16:03:20.786 - info: host.ioBroker iobroker host.ioBroker object system.adapter.bayernluft.0.logLevel created
2024-12-08 16:03:20.793 - info: host.ioBroker iobroker host.ioBroker object bayernluft.0.info created
2024-12-08 16:03:20.795 - info: host.ioBroker iobroker host.ioBroker object bayernluft.0.info.connection created
2024-12-08 16:03:20.799 - info: host.ioBroker iobroker host.ioBroker Set default value of bayernluft.0.info.connection: false
2024-12-08 16:03:20.804 - info: host.ioBroker iobroker host.ioBroker object system.adapter.bayernluft.0 created
2024-12-08 16:03:25.082 - info: host.ioBroker instance system.adapter.bayernluft.0 in version "2.0.0-alpha.0" (non-npm: iobroker-community-adapters/ioBroker.bayernluft#a4b5fc04bfc1c1af3352cdc49ed7e5263d44c568) started with pid 177400
2024-12-08 16:03:26.184 - info: bayernluft.0 (177400) starting. Version 2.0.0-alpha.0 (non-npm: iobroker-community-adapters/ioBroker.bayernluft#a4b5fc04bfc1c1af3352cdc49ed7e5263d44c568) in /opt/iobroker/node_modules/iobroker.bayernluft, node: v20.18.1, js-controller: 7.0.3
2024-12-08 16:03:26.269 - error: bayernluft.0 (177400) No devices has been set, disabling adapter!
2024-12-08 16:03:26.277 - info: host.ioBroker "system.adapter.bayernluft.0" disabled
2024-12-08 16:03:26.277 - info: host.ioBroker stopInstance system.adapter.bayernluft.0 (force=false, process=true)
2024-12-08 16:03:26.284 - info: bayernluft.0 (177400) Got terminate signal TERMINATE_YOURSELF
2024-12-08 16:03:26.284 - info: host.ioBroker stopInstance system.adapter.bayernluft.0 send kill signal
2024-12-08 16:03:26.459 - info: bayernluft.0 (177400) terminating
2024-12-08 16:03:26.460 - info: bayernluft.0 (177400) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2024-12-08 16:03:26.788 - info: bayernluft.0 (177400) terminating
2024-12-08 16:03:27.073 - info: host.ioBroker instance system.adapter.bayernluft.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2024-12-08 16:10:59.622 - info: host.ioBroker "system.adapter.bayernluft.0" enabled
2024-12-08 16:11:00.428 - info: host.ioBroker instance system.adapter.bayernluft.0 in version "2.0.0-alpha.0" (non-npm: iobroker-community-adapters/ioBroker.bayernluft#a4b5fc04bfc1c1af3352cdc49ed7e5263d44c568) started with pid 177565
2024-12-08 16:11:01.361 - info: bayernluft.0 (177565) starting. Version 2.0.0-alpha.0 (non-npm: iobroker-community-adapters/ioBroker.bayernluft#a4b5fc04bfc1c1af3352cdc49ed7e5263d44c568) in /opt/iobroker/node_modules/iobroker.bayernluft, node: v20.18.1, js-controller: 7.0.3
2024-12-08 16:11:29.774 - info: host.ioBroker stopInstance system.adapter.bayernluft.0 (force=false, process=true)
2024-12-08 16:11:29.776 - info: host.ioBroker stopInstance system.adapter.bayernluft.0 send kill signal
2024-12-08 16:11:29.777 - info: bayernluft.0 (177565) Got terminate signal TERMINATE_YOURSELF
2024-12-08 16:11:29.782 - info: bayernluft.0 (177565) terminating
2024-12-08 16:11:29.783 - info: bayernluft.0 (177565) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2024-12-08 16:11:30.284 - info: bayernluft.0 (177565) terminating
2024-12-08 16:11:30.407 - info: host.ioBroker instance system.adapter.bayernluft.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2024-12-08 16:11:33.787 - info: host.ioBroker instance system.adapter.bayernluft.0 in version "2.0.0-alpha.0" (non-npm: iobroker-community-adapters/ioBroker.bayernluft#a4b5fc04bfc1c1af3352cdc49ed7e5263d44c568) started with pid 177589
2024-12-08 16:11:34.777 - info: bayernluft.0 (177589) starting. Version 2.0.0-alpha.0 (non-npm: iobroker-community-adapters/ioBroker.bayernluft#a4b5fc04bfc1c1af3352cdc49ed7e5263d44c568) in /opt/iobroker/node_modules/iobroker.bayernluft, node: v20.18.1, js-controller: 7.0.3
2024-12-08 16:12:05.028 - warn: bayernluft.0 (177589) Object bayernluft.0.Wintergarten.parameter.temperature_in is invalid: Default value has to be type "number" but received type "string" This will throw an error up from js-controller version 7.0.0!
2024-12-08 16:12:05.149 - info: bayernluft.0 (177589) State value to set for "bayernluft.0.Wintergarten.parameter.temperature_in" has to be type "number" but received type "string"
2024-12-08 16:12:05.193 - warn: bayernluft.0 (177589) Object bayernluft.0.Wintergarten.parameter.temperature_out is invalid: Default value has to be type "number" but received type "string" This will throw an error up from js-controller version 7.0.0!
2024-12-08 16:12:05.201 - info: bayernluft.0 (177589) State value to set for "bayernluft.0.Wintergarten.parameter.temperature_out" has to be type "number" but received type "string"
2024-12-08 16:12:05.205 - warn: bayernluft.0 (177589) Object bayernluft.0.Wintergarten.parameter.temperature_fresh is invalid: Default value has to be type "number" but received type "string" This will throw an error up from js-controller version 7.0.0!
2024-12-08 16:12:05.267 - info: bayernluft.0 (177589) State value to set for "bayernluft.0.Wintergarten.parameter.temperature_fresh" has to be type "number" but received type "string"
2024-12-08 16:12:05.270 - warn: bayernluft.0 (177589) Object bayernluft.0.Wintergarten.parameter.rel_humidity_in is invalid: Default value has to be type "number" but received type "string" This will throw an error up from js-controller version 7.0.0!
2024-12-08 16:12:05.276 - info: bayernluft.0 (177589) State value to set for "bayernluft.0.Wintergarten.parameter.rel_humidity_in" has to be type "number" but received type "string"
2024-12-08 16:12:05.343 - warn: bayernluft.0 (177589) Object bayernluft.0.Wintergarten.parameter.rel_humidity_out is invalid: Default value has to be type "number" but received type "string" This will throw an error up from js-controller version 7.0.0!
2024-12-08 16:12:05.353 - info: bayernluft.0 (177589) State value to set for "bayernluft.0.Wintergarten.parameter.rel_humidity_out" has to be type "number" but received type "string"
2024-12-08 16:12:05.356 - warn: bayernluft.0 (177589) Object bayernluft.0.Wintergarten.parameter.abs_humidity_in is invalid: Default value has to be type "number" but received type "string" This will throw an error up from js-controller version 7.0.0!
2024-12-08 16:12:05.363 - info: bayernluft.0 (177589) State value to set for "bayernluft.0.Wintergarten.parameter.abs_humidity_in" has to be type "number" but received type "string"
2024-12-08 16:12:05.368 - warn: bayernluft.0 (177589) Object bayernluft.0.Wintergarten.parameter.abs_humidity_out is invalid: Default value has to be type "number" but received type "string" This will throw an error up from js-controller version 7.0.0!
2024-12-08 16:12:05.417 - info: bayernluft.0 (177589) State value to set for "bayernluft.0.Wintergarten.parameter.abs_humidity_out" has to be type "number" but received type "string"
2024-12-08 16:12:05.421 - warn: bayernluft.0 (177589) Object bayernluft.0.Wintergarten.parameter.efficiency is invalid: Default value has to be type "number" but received type "string" This will throw an error up from js-controller version 7.0.0!
2024-12-08 16:12:05.427 - info: bayernluft.0 (177589) State value to set for "bayernluft.0.Wintergarten.parameter.efficiency" has to be type "number" but received type "string"
2024-12-08 16:12:05.432 - warn: bayernluft.0 (177589) Object bayernluft.0.Wintergarten.parameter.humidity_transport is invalid: Default value has to be type "number" but received type "string" This will throw an error up from js-controller version 7.0.0!
2024-12-08 16:12:05.481 - info: bayernluft.0 (177589) State value to set for "bayernluft.0.Wintergarten.parameter.humidity_transport" has to be type "number" but received type "string"
2024-12-08 16:12:05.510 - warn: bayernluft.0 (177589) Object bayernluft.0.Wintergarten.states.systemon is invalid: Default value has to be type "number" but received type "string" This will throw an error up from js-controller version 7.0.0!
2024-12-08 16:12:05.518 - info: bayernluft.0 (177589) State value to set for "bayernluft.0.Wintergarten.states.systemon" has to be type "number" but received type "string"
2024-12-08 16:12:05.566 - warn: bayernluft.0 (177589) Object bayernluft.0.Wintergarten.states.Antifreeze is invalid: Default value has to be type "number" but received type "string" This will throw an error up from js-controller version 7.0.0!
2024-12-08 16:12:05.572 - info: bayernluft.0 (177589) State value to set for "bayernluft.0.Wintergarten.states.Antifreeze" has to be type "number" but received type "string"
2024-12-08 16:12:05.577 - warn: bayernluft.0 (177589) Object bayernluft.0.Wintergarten.states.fixed_speed is invalid: Default value has to be type "number" but received type "string" This will throw an error up from js-controller version 7.0.0!
2024-12-08 16:12:05.583 - info: bayernluft.0 (177589) State value to set for "bayernluft.0.Wintergarten.states.fixed_speed" has to be type "number" but received type "string"
2024-12-08 16:12:05.587 - warn: bayernluft.0 (177589) Object bayernluft.0.Wintergarten.states.defrosting is invalid: Default value has to be type "number" but received type "string" This will throw an error up from js-controller version 7.0.0!
2024-12-08 16:12:05.641 - info: bayernluft.0 (177589) State value to set for "bayernluft.0.Wintergarten.states.defrosting" has to be type "number" but received type "string"
2024-12-08 16:12:05.644 - warn: bayernluft.0 (177589) Object bayernluft.0.Wintergarten.states.landlord_mode is invalid: Default value has to be type "number" but received type "string" This will throw an error up from js-controller version 7.0.0!
2024-12-08 16:12:05.653 - info: bayernluft.0 (177589) State value to set for "bayernluft.0.Wintergarten.states.landlord_mode" has to be type "number" but received type "string"
2024-12-08 16:12:05.658 - warn: bayernluft.0 (177589) Object bayernluft.0.Wintergarten.states.cross_ventilation is invalid: Default value has to be type "number" but received type "string" This will throw an error up from js-controller version 7.0.0!
2024-12-08 16:12:05.668 - info: bayernluft.0 (177589) State value to set for "bayernluft.0.Wintergarten.states.cross_ventilation" has to be type "number" but received type "string"
2024-12-08 16:12:05.713 - warn: bayernluft.0 (177589) Object bayernluft.0.Wintergarten.states.timer_active is invalid: Default value has to be type "number" but received type "string" This will throw an error up from js-controller version 7.0.0!
2024-12-08 16:12:05.724 - info: bayernluft.0 (177589) State value to set for "bayernluft.0.Wintergarten.states.timer_active" has to be type "number" but received type "string"
2024-12-08 16:12:35.050 - error: bayernluft.0 (177589) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-12-08 16:12:35.051 - error: bayernluft.0 (177589) unhandled promise rejection: Parameter "ack" needs to be of type "boolean" but type "string" has been passed
2024-12-08 16:12:35.052 - error: bayernluft.0 (177589) Error: Parameter "ack" needs to be of type "boolean" but type "string" has been passed
at Bayernluft.setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/cjs/lib/adapter/adapter.js:4957:34)
at Bayernluft.setStateAsync (/opt/iobroker/node_modules/@iobroker/js-controller-common-db/build/cjs/lib/common/tools.js:1579:12)
at Bayernluft.setObjectNotExistsAsyncEasy (/opt/iobroker/node_modules/iobroker.bayernluft/main.js:193:28)
at async Bayernluft.checkDevices (/opt/iobroker/node_modules/iobroker.bayernluft/main.js:75:13)
at async Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.bayernluft/main.js:43:13)
2024-12-08 16:12:35.052 - error: bayernluft.0 (177589) Parameter "ack" needs to be of type "boolean" but type "string" has been passed
2024-12-08 16:12:35.061 - info: bayernluft.0 (177589) terminating
2024-12-08 16:12:35.061 - warn: bayernluft.0 (177589) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-12-08 16:12:35.554 - info: bayernluft.0 (177589) terminating
2024-12-08 16:12:35.671 - error: host.ioBroker instance system.adapter.bayernluft.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2024-12-08 16:12:35.671 - info: host.ioBroker Restart adapter system.adapter.bayernluft.0 because enabled
2024-12-08 16:13:06.088 - info: host.ioBroker instance system.adapter.bayernluft.0 in version "2.0.0-alpha.0" (non-npm: iobroker-community-adapters/ioBroker.bayernluft#a4b5fc04bfc1c1af3352cdc49ed7e5263d44c568) started with pid 177624
2024-12-08 16:13:06.898 - info: bayernluft.0 (177624) starting. Version 2.0.0-alpha.0 (non-npm: iobroker-community-adapters/ioBroker.bayernluft#a4b5fc04bfc1c1af3352cdc49ed7e5263d44c568) in /opt/iobroker/node_modules/iobroker.bayernluft, node: v20.18.1, js-controller: 7.0.3
2024-12-08 16:13:37.118 - error: bayernluft.0 (177624) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-12-08 16:13:37.118 - error: bayernluft.0 (177624) unhandled promise rejection: Parameter "ack" needs to be of type "boolean" but type "string" has been passed
2024-12-08 16:13:37.119 - error: bayernluft.0 (177624) Error: Parameter "ack" needs to be of type "boolean" but type "string" has been passed
at Bayernluft.setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/cjs/lib/adapter/adapter.js:4957:34)
at Bayernluft.setStateAsync (/opt/iobroker/node_modules/@iobroker/js-controller-common-db/build/cjs/lib/common/tools.js:1579:12)
at Bayernluft.setObjectNotExistsAsyncEasy (/opt/iobroker/node_modules/iobroker.bayernluft/main.js:193:28)
at async Bayernluft.checkDevices (/opt/iobroker/node_modules/iobroker.bayernluft/main.js:75:13)
at async Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.bayernluft/main.js:43:13)
2024-12-08 16:13:37.119 - error: bayernluft.0 (177624) Parameter "ack" needs to be of type "boolean" but type "string" has been passed
2024-12-08 16:13:37.127 - info: bayernluft.0 (177624) terminating
2024-12-08 16:13:37.127 - warn: bayernluft.0 (177624) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-12-08 16:13:37.624 - info: bayernluft.0 (177624) terminating
2024-12-08 16:13:37.736 - error: host.ioBroker instance system.adapter.bayernluft.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2024-12-08 16:13:37.736 - info: host.ioBroker Restart adapter system.adapter.bayernluft.0 because enabled
2024-12-08 16:14:08.317 - info: host.ioBroker instance system.adapter.bayernluft.0 in version "2.0.0-alpha.0" (non-npm: iobroker-community-adapters/ioBroker.bayernluft#a4b5fc04bfc1c1af3352cdc49ed7e5263d44c568) started with pid 177656
2024-12-08 16:14:09.229 - info: bayernluft.0 (177656) starting. Version 2.0.0-alpha.0 (non-npm: iobroker-community-adapters/ioBroker.bayernluft#a4b5fc04bfc1c1af3352cdc49ed7e5263d44c568) in /opt/iobroker/node_modules/iobroker.bayernluft, node: v20.18.1, js-controller: 7.0.3
2024-12-08 16:14:39.478 - error: bayernluft.0 (177656) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-12-08 16:14:39.479 - error: bayernluft.0 (177656) unhandled promise rejection: Parameter "ack" needs to be of type "boolean" but type "string" has been passed
2024-12-08 16:14:39.480 - error: bayernluft.0 (177656) Error: Parameter "ack" needs to be of type "boolean" but type "string" has been passed
at Bayernluft.setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/cjs/lib/adapter/adapter.js:4957:34)
at Bayernluft.setStateAsync (/opt/iobroker/node_modules/@iobroker/js-controller-common-db/build/cjs/lib/common/tools.js:1579:12)
at Bayernluft.setObjectNotExistsAsyncEasy (/opt/iobroker/node_modules/iobroker.bayernluft/main.js:193:28)
at async Bayernluft.checkDevices (/opt/iobroker/node_modules/iobroker.bayernluft/main.js:75:13)
at async Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.bayernluft/main.js:43:13)
2024-12-08 16:14:39.480 - error: bayernluft.0 (177656) Parameter "ack" needs to be of type "boolean" but type "string" has been passed
2024-12-08 16:14:39.488 - info: bayernluft.0 (177656) terminating
2024-12-08 16:14:39.488 - warn: bayernluft.0 (177656) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-12-08 16:14:39.984 - info: bayernluft.0 (177656) terminating
2024-12-08 16:14:40.106 - error: host.ioBroker instance system.adapter.bayernluft.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2024-12-08 16:14:40.107 - info: host.ioBroker Restart adapter system.adapter.bayernluft.0 because enabled
2024-12-08 16:14:40.107 - warn: host.ioBroker Do not restart adapter system.adapter.bayernluft.0 because restart loop detected
```

**Comment by mcm1957** [comment]
siehe https://forum.iobroker.net/topic/68777/bayernl%C3%BCfter-und-iobroker/25
und fork @boriswerner

**Comment by Wildbill-Z** [comment]
I think this issue should be closed, as setspeed and setauto work as expected without any errors or warnings in the log.
